# -*- coding: utf-8 -*-
"""Dash final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iDb5Pazb_kBrwCgvIZMJwy5Ybw2lv1z0
"""

import pandas as pd
import json
import math
import os
import io

GITHUB_CSV = (
    "https://raw.githubusercontent.com/"
    "Unchell57/CoffeePlusPlus/main/input/TastyCoffee.csv"
)

class CoffeeAnalyzer:
    """Хранит очищенный датафрейм и шорт-лист меню кофейни."""

    def __init__(self, source):
        """
        source- URL строка или bytes (содержимое CSV).
        Читаtn данные и сразу чистиn.
        """
        raw        = pd.read_csv(source)
        self.df    = self._clean(raw)
        self.menu  = []   # шорт-лист позиций для меню

    # Очистка данных

    def _clean(self, df):
        """
        Оставляет только граммы и килограммы
        Заполняет пустые поля
        Добавляет колонку 'Цена за 100г' для удобства.
        """
        # фильтр по единице измерения
        df = df[df["Единица"].isin(["г", "кг"])].copy()

        # исправляет опечатку и заполняет пустые значения
        df["Способ обработки"] = (
            df["Способ обработки"]
            .str.strip()
            .replace("cмесь", "смесь")
            .fillna("не указан")
        )

        #заполняет числовые и текстовые пустоты
        df["Плотность"]   = df["Плотность"].fillna(0)
        df["Кислотность"] = df["Кислотность"].fillna(0)
        df["Описание"]    = df["Описание"].fillna("")

        #удобная дополнительная колонка
        df["Цена за 100г"] = (df["Цена за кг/шт"] / 10).round(0).astype(int)

        return df.reset_index(drop=True)

    #Краткая статистика

    def stats(self):
        """Возвращает словарь с KPI для карточек дашборда."""
        d = self.df
        r = d[d["Рейтинг"] > 0]   # только те, у кого есть оценка
        return {
            "total":       len(d),
            "avg_rating":  round(float(r["Рейтинг"].mean()), 2) if len(r) else 0,
            "avg_price":   int(d["Цена за кг/шт"].mean()),
            "max_reviews": int(d["Число отзывов"].max()),
            "types":       int(d["Тип"].nunique()),
        }

    #Подбор кандидатов для меню

    def get_candidates(self, min_rating=4.5, min_reviews=100,
                       max_price=6000, types=None):
        """
        Возвращает отфильтрованный датафрейм, отсортированный по баллам.
        формула:
            Балл = Рейтинг × log10(Отзывы + 1) - штраф за цену × 0.5
        Логика формулы:
          Рейтинг- главный фактор качества,log10 даёт бонус за популярность, но сглаживает разрыв между 100 и 10 000 отзывами, штраф за цену небольшой (×0.5)
        """
        d = self.df.copy()

        # Применяю фильтры по критериям
        d = d[d["Рейтинг"]       >= min_rating ]
        d = d[d["Число отзывов"] >= min_reviews]
        d = d[d["Цена за кг/шт"] <= max_price  ]
        if types:
            d = d[d["Тип"].isin(types)]

        if d.empty:
            return d

        # Считаю балл для каждой позиции
        max_p     = d["Цена за кг/шт"].max() or 1
        d["Балл"] = (
            d["Рейтинг"] * d["Число отзывов"].apply(lambda x: math.log10(x + 1))
            - d["Цена за кг/шт"] / max_p * 0.5
        ).round(2)

        cols = ["Название", "Тип", "Способ обработки",
                "Плотность", "Кислотность",
                "Цена", "Цена за кг/шт", "Рейтинг", "Число отзывов", "Балл"]
        return d[cols].sort_values("Балл", ascending=False).reset_index(drop=True)

    #Работа с шорт-листом меню

    def add_to_menu(self, name):
        """
        Добавляет кофе в шорт-лист меню.
        """
        # поиск
        match = self.df[self.df["Название"].str.lower() == name.lower()]
        if match.empty:
            return False, f"«{name}» не найден в базе."

        real_name = match.iloc[0]["Название"]

        # проверка дубликата
        if any(i["Название"] == real_name for i in self.menu):
            return False, f"«{real_name}» уже есть в меню."

        # добавление
        row = match.iloc[0]
        self.menu.append({
            "Название":      real_name,
            "Тип":           row["Тип"],
            "Цена":          int(row["Цена"]),
            "Рейтинг":       float(row["Рейтинг"]),
            "Число отзывов": int(row["Число отзывов"]),
        })
        return True, f"✅ «{real_name}» добавлен в меню!"

    def remove_from_menu(self, name):
        """Удаляет позицию из меню по точному названию."""
        before    = len(self.menu)
        self.menu = [i for i in self.menu if i["Название"] != name]
        return (True,  f"🗑 «{name}» удалён.") if len(self.menu) < before \
          else (False, f"«{name}» не найден в меню.")

# Создаю анализатор он сам скачает и почистит данные
analyzer = CoffeeAnalyzer(GITHUB_CSV)
S = analyzer.stats()

# Все строки датафрейма для таблиц, графиков и поиска
ALL_DATA = analyzer.df.to_dict("records")

# Уникальные типы кофе- для выпадающего списка
TYPES = sorted(analyzer.df["Тип"].unique().tolist())

# Все названия- для выпадающего списка «добавить в меню»
NAMES = sorted(analyzer.df["Название"].unique().tolist())

# Сериализую в JSON
JS_DATA  = json.dumps(ALL_DATA, ensure_ascii=False)
JS_STATS = json.dumps(S,        ensure_ascii=False)

# Генерирую HTML-фрагменты для вставки в шаблон
TYPE_OPTIONS = "".join(
    f'<option value="{t}">{t}</option>' for t in TYPES
)
NAME_OPTIONS = "".join(
    f'<option value="{n}">{n}</option>' for n in NAMES
)
TYPE_CHECKBOXES = "".join(
    f'<label><input type="checkbox" value="{t}" onchange="updateCandidates()"> {t}</label>'
    for t in TYPES
)

HTML_CSS = """<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>☕ TastyCoffee Analytics</title>
  <script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
  <style>
    /* Сброс и базовые стили */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background: #1a1a1a;
      color: #f0e6d3;
      font-family: 'Segoe UI', Arial, sans-serif;
      font-size: 14px;
    }
    .page { max-width: 1400px; margin: 0 auto; padding: 24px 20px; }

    /* Заголовок */
    .site-title    { color: #c8843a; text-align: center; font-size: 2em; margin-bottom: 6px; }
    .site-subtitle { text-align: center; color: #888; margin-bottom: 24px; }

    /* KPI карточки */
    .kpi-row { display: grid; grid-template-columns: repeat(4,1fr); gap: 12px; margin-bottom: 24px; }
    .kpi     { background: #262626; border: 1px solid #5a3a1a; border-radius: 10px; padding: 18px; text-align: center; }
    .kpi-val { font-size: 1.75em; color: #c8843a; font-weight: 700; }
    .kpi-lbl { color: #888; font-size: 12px; margin-top: 4px; }

    /* Вкладки */
    .tab-bar  { display: flex; gap: 4px; border-bottom: 2px solid #5a3a1a; margin-bottom: 20px; }
    .tab-btn  { padding: 10px 22px; background: #262626; color: #888;
                border: 1px solid #444; border-bottom: none;
                border-radius: 8px 8px 0 0; cursor: pointer; font-size: 14px;
                transition: background .15s, color .15s; }
    .tab-btn:hover  { background: #333; color: #f0e6d3; }
    .tab-btn.active { background: #2e1f0e; color: #c8843a; border-color: #5a3a1a; font-weight: 600; }
    .tab-panel      { display: none; }
    .tab-panel.active { display: block; }

    /* Блоки-карточки */
    .card       { background: #262626; border: 1px solid #5a3a1a; border-radius: 10px; padding: 18px; margin-bottom: 16px; }
    .card-title { color: #c8843a; font-size: 1.05em; margin-bottom: 14px; }

    /* Формы */
    label { display: block; color: #ccc; margin-bottom: 4px; }
    select, input[type=text] {
      width: 100%; background: #333; color: #f0e6d3;
      border: 1px solid #5a3a1a; border-radius: 6px; padding: 8px 10px; font-size: 14px;
    }
    select:focus, input:focus { outline: none; border-color: #c8843a; }

    /* Сетки */
    .grid-2 { display: grid; grid-template-columns: 1fr 1fr;     gap: 16px; }
    .grid-3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; }

    /* Слайдеры */
    .slider-block  { margin-bottom: 4px; }
    .slider-row    { display: flex; align-items: center; gap: 8px; margin-top: 4px; }
    .slider-row input[type=range] { flex: 1; accent-color: #c8843a; }
    .slider-val    { color: #c8843a; font-weight: 700; min-width: 55px; text-align: right; }

    /* Чекбоксы */
    .check-group { display: flex; flex-wrap: wrap; gap: 14px; margin-top: 8px; }
    .check-group label { display: flex; align-items: center; gap: 6px; color: #f0e6d3; cursor: pointer; margin: 0; }

    /* Кнопки */
    .btn         { display: inline-block; padding: 8px 18px; border: none; border-radius: 6px; cursor: pointer; font-size: 14px; transition: opacity .15s; }
    .btn:hover   { opacity: .85; }
    .btn-primary { background: #c8843a; color: #fff; }
    .btn-danger  { background: #7a1e1e; color: #fff; padding: 3px 9px; font-size: 12px; }

    /* Таблицы */
    .tbl-wrap { overflow-x: auto; }
    .tbl      { width: 100%; border-collapse: collapse; font-size: 13px; }
    .tbl th   { background: #2e1f0e; color: #f0c070; padding: 8px 10px; text-align: left;
                border-bottom: 1px solid #5a3a1a; cursor: pointer; user-select: none; white-space: nowrap; }
    .tbl th:hover          { background: #3a2810; }
    .tbl td                { padding: 7px 10px; border: 1px solid #2e2e2e; }
    .tbl tr:nth-child(odd)  td { background: #222; }
    .tbl tr:nth-child(even) td { background: #262626; }
    .tbl tr:hover td       { background: #2e2010; }

    /* Поиск */
    .search-row       { display: flex; gap: 10px; align-items: flex-end; }
    .search-row input { flex: 1; }

    /* Вспомогательные */
    .msg     { min-height: 20px; margin-top: 8px; font-size: 13px; color: #f0c070; }
    .muted   { color: #666; padding: 20px; text-align: center; }
    .hit-cnt { color: #c8843a; font-size: 13px; margin-bottom: 10px; }
    .divider { border: none; border-top: 1px solid #3a2810; margin: 24px 0; }
    footer   { text-align: center; color: #444; font-size: 12px; padding-top: 8px; }
  </style>
</head>
"""

HTML_BODY = (
  "<body>\n<div class='page'>\n"

  #Заголовок
  f"<h1 class='site-title'>&#9749; TastyCoffee &mdash; Аналитика</h1>\n"
  f"<p class='site-subtitle'>"
  f"Позиций: {S['total']} &nbsp;&middot;&nbsp; "
  f"Типов: {S['types']} &nbsp;&middot;&nbsp; "
  f"Средний рейтинг: {S['avg_rating']} &nbsp;&middot;&nbsp; "
  f"Средняя цена/кг: {S['avg_price']} &#8381;</p>\n"

  #KPI карточки
  "<div class='kpi-row'>"
  f"<div class='kpi'><div class='kpi-val'>&#128230; {S['total']}</div>"
  "<div class='kpi-lbl'>Позиций в базе</div></div>"
  f"<div class='kpi'><div class='kpi-val'>&#11088; {S['avg_rating']}</div>"
  "<div class='kpi-lbl'>Средний рейтинг</div></div>"
  f"<div class='kpi'><div class='kpi-val'>&#128176; {S['avg_price']} &#8381;</div>"
  "<div class='kpi-lbl'>Средняя цена/кг</div></div>"
  f"<div class='kpi'><div class='kpi-val'>&#128172; {S['max_reviews']}</div>"
  "<div class='kpi-lbl'>Макс. отзывов</div></div>"
  "</div>\n"

  #Кнопки вкладок
  "<div class='tab-bar'>"
  "<button class='tab-btn active' onclick=\"showTab('charts',this)\">&#128202; Графики</button>"
  "<button class='tab-btn' onclick=\"showTab('cands',this)\">&#128203; Подбор меню</button>"
  "<button class='tab-btn' onclick=\"showTab('menu',this)\">&#11088; Моё меню</button>"
  "<button class='tab-btn' onclick=\"showTab('search',this)\">&#128269; Поиск</button>"
  "</div>\n"

  #Вкладка 1: Графики
  "<div id='tab-charts' class='tab-panel active'>"
  "<div class='card'><div class='grid-2'>"
  "<div><label>Тип кофе:</label>"
  "<select id='dd-type' onchange='updateChart()'>"
  "<option value='все'>Все типы</option>"
  f"{TYPE_OPTIONS}"
  "</select></div>"
  "<div><label>График:</label>"
  "<select id='dd-chart' onchange='updateChart()'>"
  "<option value='price'>&#128176; Распределение цен</option>"
  "<option value='bubble'>&#128309; Кислотность / Плотность</option>"
  "<option value='proc'>&#127981; Рейтинг по обработке</option>"
  "<option value='pr'>&#128200; Цена vs Рейтинг</option>"
  "<option value='rev'>&#128172; Отзывы vs Рейтинг</option>"
  "<option value='types'>&#128193; Обзор типов</option>"
  "</select></div></div></div>"
  "<div id='plot-area' style='min-height:480px;'></div>"
  "</div>\n"

  #Вкладка 2: Подбор меню
  "<div id='tab-cands' class='tab-panel'>"
  "<div class='card'><div class='card-title'>Критерии отбора</div>"
  "<div class='grid-3'>"

  "<div class='slider-block'><label>Мин. рейтинг</label>"
  "<div class='slider-row'>"
  "<input type='range' id='sl-rating' min='4.0' max='5.0' step='0.1' value='4.5'"
  " oninput=\"sv('vr',this.value);updateCandidates()\">"
  "<span class='slider-val' id='vr'>4.5</span></div></div>"

  "<div class='slider-block'><label>Мин. число отзывов</label>"
  "<div class='slider-row'>"
  "<input type='range' id='sl-reviews' min='0' max='2000' step='50' value='100'"
  " oninput=\"sv('vrev',this.value);updateCandidates()\">"
  "<span class='slider-val' id='vrev'>100</span></div></div>"

  "<div class='slider-block'><label>Макс. цена/кг (&#8381;)</label>"
  "<div class='slider-row'>"
  "<input type='range' id='sl-price' min='1000' max='15000' step='500' value='6000'"
  " oninput=\"sv('vp',this.value);updateCandidates()\">"
  "<span class='slider-val' id='vp'>6000</span></div></div>"
  "</div>"

  "<div style='margin-top:14px;'><label>Типы кофе (пусто = все):</label>"
  f"<div class='check-group'>{TYPE_CHECKBOXES}</div></div>"
  "</div>"
  "<div id='cands-out'></div></div>\n"

  #Вкладка 3: Моё меню
  "<div id='tab-menu' class='tab-panel'>"
  "<div class='card'><div class='card-title'>Добавить в меню</div>"
  "<div class='grid-2' style='align-items:flex-end;'>"
  "<div><label>Выберите кофе:</label>"
  "<select id='dd-add'><option value=''>— выберите —</option>"
  f"{NAME_OPTIONS}</select></div>"
  "<div><button class='btn btn-primary' onclick='addToMenu()'>&#10133; Добавить</button></div>"
  "</div><div class='msg' id='msg-menu'></div></div>"
  "<div id='menu-out'></div></div>\n"

  #Вкладка 4: Поиск
  "<div id='tab-search' class='tab-panel'>"
  "<div class='card'><div class='card-title'>Поиск по названию или описанию</div>"
  "<div class='search-row'>"
  "<input type='text' id='inp-q'"
  " placeholder='Эфиопия, ягоды, натуральный, без кофеина...'"
  " onkeydown=\"if(event.key==='Enter')doSearch()\">"
  "<button class='btn btn-primary' onclick='doSearch()'>&#128269; Найти</button>"
  "</div></div><div id='search-out'></div></div>\n"

  "<hr class='divider'>"
  "<footer>TastyCoffee Analytics &nbsp;&middot;&nbsp; "
  "данные: github.com/Unchell57/CoffeePlusPlus</footer>"
  "</div>"
)

HTML_SCRIPT = """
<script>

//  Данные, вшитые из Python
// Весь датасет (66 строк) лежит прямо в файле — сервер не нужен
const DATA  = """ + JS_DATA  + """;
const STATS = """ + JS_STATS + """;

// Список меню хранится в памяти страницы
let myMenu = [];

// Состояние сортировки таблицы кандидатов
let candSort = { col: "Балл", dir: -1 };  // -1 = убывание, 1 = возрастание

// Цвета для каждого типа кофе на графиках
const COLORS = {
  "для эспрессо": "#c8843a",
  "для фильтра":  "#4a90d9",
  "омни":         "#7ac87a",
};


//  ВКЛАДКИ

function showTab(name, btn) {
  // Скрываем все панели и убираем активный стиль
  document.querySelectorAll(".tab-panel").forEach(p => p.classList.remove("active"));
  document.querySelectorAll(".tab-btn")  .forEach(b => b.classList.remove("active"));
  // Показываем нужную панель
  document.getElementById("tab-" + name).classList.add("active");
  btn.classList.add("active");
  // При открытии вкладки строим её содержимое
  if (name === "charts") updateChart();
  if (name === "cands")  updateCandidates();
  if (name === "menu")   renderMenu();
}


//  ОБЩИЕ ВСПОМОГАТЕЛЬНЫЕ ФУНКЦИИ

// Обновляет подпись рядом со слайдером
function sv(id, val) { document.getElementById(id).textContent = val; }

// Фильтрует DATA по типу кофе ("все" = вернуть всё)
function byType(type) {
  return type === "все" ? DATA : DATA.filter(d => d["Тип"] === type);
}

// Среднее значение массива (только числа больше 0)
function avg(arr) {
  const a = arr.filter(x => x > 0);
  return a.length ? a.reduce((s, x) => s + x, 0) / a.length : 0;
}

// Общий тёмный layout для всех графиков Plotly
function darkLayout(title, extra) {
  return Object.assign({
    title:         { text: title, font: { color: "#f0e6d3" } },
    paper_bgcolor: "#1a1a1a",
    plot_bgcolor:  "#222",
    font:          { color: "#f0e6d3", size: 13 },
    height:        480,
    legend:        { bgcolor: "#262626", bordercolor: "#444" },
    xaxis:         { gridcolor: "#333", zerolinecolor: "#444" },
    yaxis:         { gridcolor: "#333", zerolinecolor: "#444" },
  }, extra || {});
}

// Строит HTML-таблицу; клик по заголовку вызывает sortFn(key)
function buildTable(rows, cols, sortFn) {
  if (!rows.length) return "<p class='muted'>Нет данных.</p>";

  const head = cols.map(c => {
    const arrow = (candSort.col === c.key)
      ? (candSort.dir === 1 ? " ▲" : " ▼") : "";
    // Сохраняем функцию сортировки глобально, чтобы onclick нашёл её
    window._sortFn = sortFn;
    return `<th onclick="window._sortFn('${c.key}')">${c.label}${arrow}</th>`;
  }).join("");

  const body = rows.map(r => {
    const cells = cols.map(c => {
      const v = r[c.key];
      return `<td>${c.fmt ? c.fmt(v) : (v ?? "")}</td>`;
    }).join("");
    return `<tr>${cells}</tr>`;
  }).join("");

  return `<table class="tbl">
    <thead><tr>${head}</tr></thead>
    <tbody>${body}</tbody>
  </table>`;
}


//  ВКЛАДКА 1: ГРАФИКИ

function updateChart() {
  const type  = document.getElementById("dd-type") .value;
  const chart = document.getElementById("dd-chart").value;
  const data  = byType(type);

  // Диспетчер — вызываем нужную функцию по ключу
  const draw = {
    price:  () => drawPrice(data),
    bubble: () => drawBubble(data),
    proc:   () => drawProc(),
    pr:     () => drawPriceRating(data),
    rev:    () => drawReviews(data),
    types:  () => drawTypes(),
  };
  (draw[chart] || draw.price)();
}

// График 1: гистограмма цен (слева) + box plot по типам (справа)
function drawPrice(data) {
  const hist = {
    x: data.map(d => d["Цена за кг/шт"]),
    type: "histogram", nbinsx: 20,
    marker: { color: "#c8843a" }, name: "Цена/кг",
    xaxis: "x", yaxis: "y",
  };
  const boxes = [...new Set(data.map(d => d["Тип"]))].map(t => ({
    y:    data.filter(d => d["Тип"] === t).map(d => d["Цена за кг/шт"]),
    type: "box", name: t,
    marker: { color: COLORS[t] || "#888" },
    xaxis: "x2", yaxis: "y2",
  }));
  Plotly.newPlot("plot-area", [hist, ...boxes], darkLayout(
    "Распределение цен на кофе", {
      grid:   { rows: 1, columns: 2, pattern: "independent" },
      xaxis:  { title: "Цена ₽/кг" },
      yaxis:  { title: "Количество" },
      yaxis2: { title: "Цена ₽/кг" },
  }), { responsive: true });
}

// График 2: пузырьковая диаграмма
// Оси: кислотность (X) и плотность (Y)
// Размер пузырька = число отзывов, цвет = рейтинг
function drawBubble(data) {
  const d = data.filter(r => r["Рейтинг"] > 0 && r["Плотность"] > 0);
  const traces = [...new Set(d.map(r => r["Тип"]))].map(t => {
    const s = d.filter(r => r["Тип"] === t);
    return {
      x: s.map(r => r["Кислотность"]),
      y: s.map(r => r["Плотность"]),
      mode: "markers", type: "scatter", name: t,
      marker: {
        size:      s.map(r => Math.max(8, Math.sqrt(r["Число отзывов"] + 1) * 1.5)),
        color:     s.map(r => r["Рейтинг"]),
        colorscale:"YlOrBr",
        showscale: t === [...new Set(d.map(r => r["Тип"]))][0],
        colorbar:  { title: "Рейтинг", x: 1.02 },
        line:      { color: "#444", width: 1 },
      },
      text: s.map(r =>
        `${r["Название"]}<br>Рейтинг: ${r["Рейтинг"]}<br>` +
        `Цена: ${r["Цена"]} ₽<br>Отзывов: ${r["Число отзывов"]}`),
      hovertemplate: "%{text}<extra></extra>",
    };
  });
  Plotly.newPlot("plot-area", traces, darkLayout(
    "Кислотность vs Плотность (размер = отзывы, цвет = рейтинг)", {
      xaxis: { title: "Кислотность" },
      yaxis: { title: "Плотность" },
  }), { responsive: true });
}

// График 3: горизонтальный бар — средний рейтинг по способу обработки
function drawProc() {
  const d = DATA.filter(r =>
    r["Рейтинг"] > 0 && r["Способ обработки"] !== "не указан"
  );
  // Группируем данные по способу обработки
  const g = {};
  d.forEach(r => {
    const k = r["Способ обработки"];
    if (!g[k]) g[k] = { ratings: [], reviews: [], n: 0 };
    g[k].ratings.push(r["Рейтинг"]);
    g[k].reviews.push(r["Число отзывов"]);
    g[k].n++;
  });
  const labels = Object.keys(g);
  const aRat   = labels.map(k => avg(g[k].ratings));
  const aRev   = labels.map(k => avg(g[k].reviews));
  const counts = labels.map(k => g[k].n);
  // Сортируем по возрастанию (Plotly рисует снизу вверх)
  const idx = aRat.map((_, i) => i).sort((a, b) => aRat[a] - aRat[b]);

  Plotly.newPlot("plot-area", [{
    x: idx.map(i => aRat[i]),
    y: idx.map(i => labels[i]),
    type: "bar", orientation: "h",
    marker: {
      color:     idx.map(i => aRev[i]),
      colorscale:"YlOrBr",
      showscale: true,
      colorbar:  { title: "Ср. отзывов" },
    },
    text:          idx.map(i => `${aRat[i].toFixed(2)} (${counts[i]} поз.)`),
    textposition:  "outside",
    hovertemplate: "%{y}<br>Рейтинг: %{x:.2f}<extra></extra>",
  }], darkLayout("Средний рейтинг по способу обработки", {
    height: 520,
    xaxis:  { range: [4.0, 5.1], title: "Средний рейтинг" },
    margin: { l: 220 },
  }), { responsive: true });
}

// График 4: scatter — цена vs рейтинг (размер точки = число отзывов)
function drawPriceRating(data) {
  const d = data.filter(r => r["Рейтинг"] > 0);
  const traces = [...new Set(d.map(r => r["Тип"]))].map(t => {
    const s = d.filter(r => r["Тип"] === t);
    return {
      x: s.map(r => r["Цена за кг/шт"]),
      y: s.map(r => r["Рейтинг"]),
      mode: "markers", type: "scatter", name: t,
      marker: {
        size:    s.map(r => Math.max(6, Math.sqrt(r["Число отзывов"] + 1))),
        color:   COLORS[t] || "#888",
        opacity: 0.85,
      },
      text: s.map(r => r["Название"]),
      hovertemplate: "%{text}<br>Цена: %{x} ₽<br>Рейтинг: %{y}<extra></extra>",
    };
  });
  Plotly.newPlot("plot-area", traces, darkLayout(
    "Цена vs Рейтинг (размер = число отзывов)", {
      xaxis: { title: "Цена ₽/кг" },
      yaxis: { title: "Рейтинг", range: [4.0, 5.1] },
  }), { responsive: true });
}

// График 5: scatter — число отзывов vs рейтинг (логарифмическая ось X)
function drawReviews(data) {
  const d = data.filter(r => r["Рейтинг"] > 0);
  const traces = [...new Set(d.map(r => r["Тип"]))].map(t => {
    const s = d.filter(r => r["Тип"] === t);
    return {
      x: s.map(r => r["Число отзывов"]),
      y: s.map(r => r["Рейтинг"]),
      mode: "markers", type: "scatter", name: t,
      marker: { size: 9, color: COLORS[t] || "#888", opacity: 0.85 },
      text: s.map(r => r["Название"]),
      hovertemplate: "%{text}<br>Отзывов: %{x}<br>Рейтинг: %{y}<extra></extra>",
    };
  });
  Plotly.newPlot("plot-area", traces, darkLayout(
    "Популярность vs Рейтинг (лог. шкала)", {
      xaxis: { title: "Число отзывов (лог)", type: "log" },
      yaxis: { title: "Рейтинг", range: [4.0, 5.1] },
  }), { responsive: true });
}

// График 6: бары (количество позиций) + линия (средняя цена) — двойная ось Y
function drawTypes() {
  const types  = [...new Set(DATA.map(d => d["Тип"]))];
  const counts = types.map(t => DATA.filter(d => d["Тип"] === t).length);
  const prices = types.map(t => {
    const s = DATA.filter(d => d["Тип"] === t);
    return Math.round(avg(s.map(d => d["Цена за кг/шт"])));
  });
  Plotly.newPlot("plot-area", [
    { x: types, y: counts, type: "bar",
      name: "Позиций", marker: { color: "#6F4E37" }, yaxis: "y" },
    { x: types, y: prices, type: "scatter", mode: "lines+markers",
      name: "Средняя цена ₽/кг",
      line: { color: "#f0c070", width: 3 }, yaxis: "y2" },
  ], Object.assign(darkLayout("Типы кофе: количество и средняя цена"), {
    yaxis:  { title: "Кол-во позиций" },
    yaxis2: { title: "Средняя цена ₽/кг", overlaying: "y", side: "right" },
  }), { responsive: true });
}


//  ВКЛАДКА 2: ПОДБОР КАНДИДАТОВ

function updateCandidates() {
  const minR = parseFloat(document.getElementById("sl-rating") .value);
  const minV = parseInt  (document.getElementById("sl-reviews").value);
  const maxP = parseFloat(document.getElementById("sl-price")  .value);

  // Собираем отмеченные типы
  const checked = [...document.querySelectorAll(".check-group input:checked")]
    .map(el => el.value);

  // Фильтрация по критериям
  let d = DATA.filter(r =>
    r["Рейтинг"]       >= minR &&
    r["Число отзывов"] >= minV &&
    r["Цена за кг/шт"] <= maxP &&
    (checked.length === 0 || checked.includes(r["Тип"]))
  );

  // Считаем балл: рейтинг × log(отзывы) − штраф за цену
  const maxPrice = Math.max(...d.map(r => r["Цена за кг/шт"]), 1);
  d = d.map(r => ({
    ...r,
    Балл: +(
      r["Рейтинг"] * Math.log10(r["Число отзывов"] + 1)
      - r["Цена за кг/шт"] / maxPrice * 0.5
    ).toFixed(2),
  }));

  // Сортировка по текущему столбцу
  d.sort((a, b) => (a[candSort.col] > b[candSort.col] ? 1 : -1) * candSort.dir);

  const out = document.getElementById("cands-out");

  if (!d.length) {
    out.innerHTML = "<p class='muted'>Нет подходящих позиций. Смягчите критерии.</p>";
    return;
  }

  const cols = [
    { key: "Название",         label: "Название" },
    { key: "Тип",              label: "Тип" },
    { key: "Способ обработки", label: "Обработка" },
    { key: "Плотность",        label: "Плотн." },
    { key: "Кислотность",      label: "Кислотн." },
    { key: "Цена",             label: "Цена",    fmt: v => v + " ₽" },
    { key: "Рейтинг",          label: "Рейтинг", fmt: v => "⭐ " + v },
    { key: "Число отзывов",    label: "Отзывов" },
    { key: "Балл",             label: "Балл 🏆" },
  ];

  // Функция сортировки: клик меняет направление если столбец тот же
  function onSort(col) {
    candSort = { col, dir: candSort.col === col ? -candSort.dir : -1 };
    updateCandidates();
  }

  out.innerHTML =
    `<div class="card">` +
    `<div class="hit-cnt">Найдено: ${d.length} кандидатов</div>` +
    `<div class="tbl-wrap">${buildTable(d, cols, onSort)}</div>` +
    `</div>`;
}


// ВКЛАДКА 3: МОЁ МЕНЮ

function addToMenu() {
  const name = document.getElementById("dd-add").value;
  const msg  = document.getElementById("msg-menu");

  if (!name) { msg.textContent = "⚠️ Выберите кофе из списка."; return; }

  // Проверяем, не добавлен ли уже
  if (myMenu.some(i => i["Название"] === name)) {
    msg.textContent = `«${name}» уже есть в меню.`;
    return;
  }

  // Ищем в данных
  const row = DATA.find(d => d["Название"] === name);
  if (!row) { msg.textContent = "Не найдено."; return; }

  // Добавляем в список
  myMenu.push({
    "Название":      row["Название"],
    "Тип":           row["Тип"],
    "Цена":          row["Цена"] + " ₽",
    "Рейтинг":       row["Рейтинг"],
    "Число отзывов": row["Число отзывов"],
  });

  msg.textContent = `✅ «${name}» добавлен в меню!`;
  renderMenu();
}

function removeFromMenu(name) {
  myMenu = myMenu.filter(i => i["Название"] !== name);
  document.getElementById("msg-menu").textContent = `🗑 «${name}» удалён.`;
  renderMenu();
}

function renderMenu() {
  const out = document.getElementById("menu-out");

  if (!myMenu.length) {
    out.innerHTML =
      "<div class='card'><p class='muted'>Меню пустое. Добавьте кофе выше.</p></div>";
    return;
  }

  const rows = myMenu.map(i => {
    // Экранируем кавычки в названии для безопасного onclick
    const safe = i["Название"].replace(/'/g, "\\\\'");
    return `<tr>
      <td>${i["Название"]}</td>
      <td style="color:#888">${i["Тип"]}</td>
      <td style="color:#f0c070">${i["Цена"]}</td>
      <td>⭐ ${i["Рейтинг"]}</td>
      <td style="color:#888">${Number(i["Число отзывов"]).toLocaleString()}</td>
      <td><button class="btn btn-danger"
          onclick="removeFromMenu('${safe}')">✕</button></td>
    </tr>`;
  }).join("");

  out.innerHTML =
    `<div class="card">` +
    `<div class="card-title">В меню: ${myMenu.length} позиций</div>` +
    `<div class="tbl-wrap"><table class="tbl"><thead><tr>` +
    `<th>Название</th><th>Тип</th><th>Цена</th>` +
    `<th>Рейтинг</th><th>Отзывов</th><th></th>` +
    `</tr></thead><tbody>${rows}</tbody></table></div></div>`;
}


// ВКЛАДКА 4: ПОИСК

function doSearch() {
  const q   = document.getElementById("inp-q").value.trim().toLowerCase();
  const out = document.getElementById("search-out");

  if (!q) {
    out.innerHTML = "<p class='muted'>Введите поисковый запрос.</p>";
    return;
  }

  // Ищем подстроку в названии и описании
  const res = DATA.filter(d =>
    d["Название"].toLowerCase().includes(q) ||
    (d["Описание"] || "").toLowerCase().includes(q)
  );

  if (!res.length) {
    out.innerHTML = `<p class='muted'>Ничего не найдено по «${q}».</p>`;
    return;
  }

  const cols = [
    { key: "Название",         label: "Название" },
    { key: "Тип",              label: "Тип" },
    { key: "Способ обработки", label: "Обработка" },
    { key: "Плотность",        label: "Плотн." },
    { key: "Кислотность",      label: "Кислотн." },
    { key: "Цена",             label: "Цена", fmt: v => v + " ₽" },
    { key: "Рейтинг",          label: "Рейтинг" },
    { key: "Число отзывов",    label: "Отзывов" },
  ];

  out.innerHTML =
    `<div class="card">` +
    `<div class="hit-cnt">Найдено: ${res.length} по «${q}»</div>` +
    `<div class="tbl-wrap">${buildTable(res, cols, () => {})}</div>` +
    `</div>`;
}


// ИНИЦИАЛИЗАЦИЯ
// Строим первый график и таблицу кандидатов при загрузке страницы
window.onload = function() {
  updateChart();
  updateCandidates();
};

</script>
</body>
</html>"""

# Склейка стили + разметка + JavaScript
FINAL_HTML = HTML_CSS + HTML_BODY + HTML_SCRIPT

OUT = "/content/coffee_dashboard.html"
with open(OUT, "w", encoding="utf-8") as f:
    f.write(FINAL_HTML)

size_kb = os.path.getsize(OUT) // 1024

from google.colab import files as _colab_files
_colab_files.download(OUT)